'use client'

import { useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { Sparkles, AlertTriangle, TrendingUp } from 'lucide-react'
import type { PropertyWithRelations } from '@/types/database'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { formatDate } from '@/lib/utils/format'

interface Props {
  propertyId: string
  property: PropertyWithRelations
}

export function AISummary({ propertyId, property }: Props) {
  const queryClient = useQueryClient()
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const score = property.opportunity_score
  const hasSummary = Boolean(score?.ai_summary)

  const handleGenerate = async () => {
    setIsGenerating(true)
    setError(null)
    try {
      const res = await fetch(`/api/properties/${propertyId}/ai-summary`, {
        method: 'POST',
      })
      if (!res.ok) throw new Error('Failed to generate AI summary')
      // Invalidate property query to get the updated summary
      await queryClient.invalidateQueries({ queryKey: ['property', propertyId] })
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Unknown error')
    } finally {
      setIsGenerating(false)
    }
  }

  if (!hasSummary) {
    return (
      <Card>
        <CardContent className="py-12 flex flex-col items-center text-center">
          <div className="w-12 h-12 rounded-full bg-teal-500/10 flex items-center justify-center mb-4">
            <Sparkles className="w-6 h-6 text-teal-400" />
          </div>
          <h3 className="text-sm font-semibold text-slate-200 mb-2">AI Deal Analysis</h3>
          <p className="text-sm text-slate-400 max-w-sm mb-6">
            Generate an AI-powered deal narrative including risk and upside analysis for this
            property.
          </p>
          {error && (
            <p className="text-xs text-red-400 mb-4">{error}</p>
          )}
          <Button
            variant="primary"
            loading={isGenerating}
            onClick={handleGenerate}
          >
            {isGenerating ? 'Generating...' : 'Generate AI Analysis'}
          </Button>
          {isGenerating && (
            <p className="text-xs text-slate-500 mt-3">
              This may take 5–10 seconds&hellip;
            </p>
          )}
        </CardContent>
      </Card>
    )
  }

  const riskFlags = score?.risk_flags ?? []
  const upsideFlags = score?.upside_flags ?? []

  return (
    <div className="space-y-4">
      {/* Summary paragraph */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-teal-400" />
            <CardTitle>AI Deal Summary</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-slate-300 leading-relaxed">{score?.ai_summary}</p>
          <div className="flex items-center gap-2 mt-4 pt-3 border-t border-slate-700/40">
            <span className="text-[10px] text-slate-500">
              Generated by GPT-4o &middot; {formatDate(score?.scored_at)}
            </span>
          </div>
        </CardContent>
      </Card>

      {/* Risk + Upside columns */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Risk */}
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-red-400" />
              <CardTitle className="text-red-400">Risk Analysis</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            {score?.ai_risk_analysis && (
              <p className="text-xs text-slate-400 mb-3 leading-relaxed">{score.ai_risk_analysis}</p>
            )}
            {riskFlags.length === 0 ? (
              <p className="text-xs text-slate-500">No risk flags identified.</p>
            ) : (
              <ul className="space-y-1.5">
                {riskFlags.map((flag, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-slate-300">
                    <span className="mt-0.5 shrink-0 w-1.5 h-1.5 rounded-full bg-red-400" />
                    {flag}
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Upside */}
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-green-400" />
              <CardTitle className="text-green-400">Upside Analysis</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            {score?.ai_upside_analysis && (
              <p className="text-xs text-slate-400 mb-3 leading-relaxed">
                {score.ai_upside_analysis}
              </p>
            )}
            {upsideFlags.length === 0 ? (
              <p className="text-xs text-slate-500">No upside flags identified.</p>
            ) : (
              <ul className="space-y-1.5">
                {upsideFlags.map((flag, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-slate-300">
                    <span className="mt-0.5 shrink-0 w-1.5 h-1.5 rounded-full bg-green-400" />
                    {flag}
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Regenerate */}
      <div className="flex justify-end">
        <Button
          variant="ghost"
          size="sm"
          loading={isGenerating}
          onClick={handleGenerate}
        >
          <Sparkles className="w-3.5 h-3.5" />
          Regenerate Analysis
        </Button>
      </div>
    </div>
  )
}
